name: Auto PR

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR if missing
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Hello from auto-pr"
